In [5]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv(r"C:\Users\haz\Downloads\car_fuel_efficiency_2026.csv")

In [7]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [8]:
df.shape

(10000, 11)

10000 records in the dataset

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

3 types are presented in the dataset

In [10]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

2 columns in the dataset have missing values

In [12]:

df.describe(include = "all")

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000,10000,10000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
unique,NaN,3,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,USA,Gasoline,Front-wheel drive,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,4202,6913,5519,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,1999.549500,NaN,NaN,NaN,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,NaN,NaN,NaN,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,NaN,NaN,NaN,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,NaN,NaN,NaN,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,NaN,NaN,NaN,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,NaN,NaN,NaN,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,NaN,NaN,NaN,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [13]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

41.2

the maximum fuel efficiency of cars from Asia

In [14]:
df["horsepower"].median()

254.0

In [15]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [16]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mode()[0])

In [17]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower             10000
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [18]:
df["horsepower"].median()

252.0

Yes, it decreased

In [19]:
df[df["origin"] == "Asia"]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [20]:
df[df["origin"] == "Asia"].shape

(2994, 11)

In [21]:
df[["vehicle_weight", "model_year"]]

      vehicle_weight  model_year
0               3870        2006
1               4210        2008
2               4240        1996
3               4490        1989
4               4510        1994
...              ...         ...
9995            4690        2005
9996            4370        1993
9997            4590        2014
9998            4450        2004
9999            4370        2011

[10000 rows x 2 columns]

In [22]:
df[df["origin"] == "Asia"].iloc[:7]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
16,2021,Asia,Gasoline,All-wheel drive,5,2280,6,234.0,4750,20.1,29.7
22,2019,Asia,Gasoline,Front-wheel drive,5,2350,6,246.0,4450,18.7,32.7

In [24]:
X = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]].iloc[:7].to_numpy()

print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [26]:
XTX = X.T @ X
print(X) #before Transpose
print(X.T) #Transpose
print(XTX) #result

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]
[[131950500  60750580]
 [ 60750580  28041424]]

In [30]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [31]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [33]:
print(y)

[1100 1300  800  900 1000 1100 1200]

In [36]:
w = XTX_inv @ X.T @ y
print(w)

[0.13644777 0.2327492 ]

In [37]:
print(w.sum())

0.3691969690492649